name: Projeto Integrador III

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'  # Garante que apenas mudanças na pasta 'front-end' acionem o workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar dependências
        run: |
          cd front-end
          npm install

      - name: Construir projeto
        run: |
          cd front-end
          npm run build

      - name: Fazer deploy
        run: |
          cd front-end
          # Comando de deploy específico (ajuste conforme necessário)
          npm run deploy
