name: Build and Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          pwd
          cd observer-pi3/Front-end
          npm install

      - name: Deploying
        run: |
          echo "Deploying the Front-end"
          ls -la
          npm run deploy
